name: WF test

on:
  workflow_dispatch:

jobs:
  job-config:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      cancel: ${{ steps.prebuild-checks.outputs.cancel }}
    defaults:
      run:
        shell: bash
    steps:
    - name: "PRE-BUILD CHECKS" 
      id: prebuild-checks
      run: |
        echo "cancel=false" >>  $GITHUB_OUTPUT


    - name: "⏬ Checkout repository"
      if: ${{ steps.prebuild-checks.outputs.cancel }} != 'true'
      uses: actions/checkout@v3


    - name: "DETECT CONFIGS"
      id: set-matrix
      if: ${{ steps.prebuild-checks.outputs.cancel }} != 'true'
      shell: pwsh
      run: |
        $m=@{include = @()}
        (gci *.dif).baseName | % { $m.include+=@{config = $_} } 
        "MATRIX:"
        $m | ConvertTo-Json
        "MATRIX STRING:"
        "matrix=$(($m | ConvertTo-Json -compress) -replace '"','`"')"
        "matrix=$(($m | ConvertTo-Json -compress) -replace '"','`"')" >> $env:GITHUB_OUTPUT


    - name: "✔️ TEST matrix"
      if: ${{ steps.prebuild-checks.outputs.cancel }} != 'true'
      run: |
        echo "MATRIX:"
        echo ${{ steps.set-matrix.outputs.matrix }}
        echo "CANCEL:"
        echo ${{ steps.prebuild-checks.outputs.cancel }}


  job-build:
    needs: [ job-config ]
    if: ${{ needs.job-config.outputs.cancel }} != 'true'
    name: "Build configuration ${{ matrix.config }}"
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ FromJson(needs.job-config.outputs.matrix) }}
        # config: ${{ FromJson(needs.job-config.outputs.configs) }}
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
    - name: "✔️ TEST matrix"
      run: |
        echo "MATRIX:"
        echo ${{ needs.job-config.outputs.matrix }}
        echo "CONFIG:"
        echo ${{ matrix.config }}
        echo "CANCEL:"
        echo ${{ needs.job-config.outputs.cancel }}
        echo "${{ matrix.config }}" >> "Kernel_${{ matrix.config }}"
    - name: "👍 Upload Artifact"
      uses: actions/upload-artifact@v3
      with:
        name: Kernel_${{ matrix.config }}
        path: |
          Kernel_*

  job-publish:
    if: ${{ needs.job-config.outputs.cancel }} != 'true'
    needs:
    - job-config
    - job-build
    name: "Publish"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: "✔️ TEST matrix"
      run: |
        echo "MATRIX:"
        echo ${{ needs.job-config.outputs.matrix }}
        echo ${{ needs.job-config.outputs.matrix }} | jq .
        echo "CANCEL:"
        echo ${{ needs.job-config.outputs.cancel }}
