name: WF test

on:
  workflow_dispatch:

jobs:
  job-config:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      configs: ${{ steps.set-matrix.outputs.configs }}
      cancel: ${{ steps.prebuild-checks.outputs.cancel }}
    defaults:
      run:
        shell: bash
    steps:
    - name: "PRE-BUILD CHECKS" 
      id: prebuild-checks
      run: |
        echo "cancel=false" >>  $GITHUB_OUTPUT


    - name: "⏬ Checkout repository"
      uses: actions/checkout@v3


    - name: "DETECT CONFIGS"
      id: set-matrix
      shell: pwsh
      run: |
        $m=@{include = @()}
        (gci *.dif).baseName | % { $m.include+=@{config = $_} } 
        "MATRIX:"
        $m | ConvertTo-Json
        "MATRIX STRING:"
        "matrix=$(($m | ConvertTo-Json -compress) -replace '"','`"')"
        "matrix=$(($m | ConvertTo-Json -compress) -replace '"','`"')" >> $env:GITHUB_OUTPUT


    - name: "✔️ TEST matrix"
      run: |
        echo "MATRIX:"
        echo ${{ steps.set-matrix.outputs.matrix }}
        echo "CANCEL:"
        echo ${{ steps.prebuild-checks.outputs.cancel }}


  job-build:
    needs: [ job-config ]
    name: "Build configuration ${{ matrix.config }}"
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ FromJson(needs.job-config.outputs.matrix) }}
        # config: ${{ FromJson(needs.job-config.outputs.configs) }}
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
    - name: "✔️ TEST matrix"
      run: |
        echo "MATRIX:"
        echo ${{ needs.job-config.outputs.matrix }}
        echo "CONFIG:"
        echo ${{ matrix.config }}
        echo "CANCEL:"
        echo ${{ needs.job-config.outputs.cancel }}

  job-publish:
    needs:
    - job-build
    - job-config
    name: "Publish"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: "✔️ TEST matrix"
      run: |
        echo "MATRIX:"
        echo ${{ needs.job-config.outputs.matrix }}
        echo "CANCEL:"
        echo ${{ needs.job-config.outputs.cancel }}
